# Generated by Django 3.2 on 2023-07-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nota', models.CharField(max_length=200)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.alumno')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.docente'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateField()),
                ('asistencia', models.CharField(choices=[('AS', 'Asistió'), ('NA', 'No asistió')], max_length=2, null=True)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.alumno')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.curso')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.horario')),
            ],
        ),
    ]
